apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: html-volume
    ports:
    - containerPort: 80
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "wget -O /work-dir/index.html http://neverssl.com/online"]
    volumeMounts:
    - mountPath: /work-dir
      name: html-volume 
  volumes:
  - name: html-volume
    emptyDir: {}

