apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 8100
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pvc-pod-ss
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: ss-azure-disk
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: ss-azure-disk
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "azurefile"
      resources:
        requests:
          storage: 4Gi

